#!/usr/bin/env python3
"""Build the 3x Bigger Worlds mod.

Reads vanilla Stellaris files from the local Steam install and generates two
sets of overrides:

  1. `mod/common/scripted_variables/zz_bworlds_planet_sizes.txt` — redefines
     the four habitable planet/moon size variables (`@habitable_planet_min_size`
     etc.) and the two strategic-resource district variables
     (`@DISTRICTS_FROM_SR_DEPOSITS{,_SMALL}`) at MULTIPLIER times the vanilla
     value. The `zz_` filename prefix puts our redefinition last in
     alphabetical load order, after vanilla's `100_scripted_variables_zones.txt`.

  2. `mod/common/deposits/*.txt` — for every vanilla deposit file, a
     same-named override with all *positive* `district_*_max_add` /
     `district_*_min_add` values multiplied by MULTIPLIER, and every numeric
     resource amount inside `produces = { ... }` blocks multiplied by
     MULTIPLIER. Negative values (blockers) and `@VAR` references are left
     alone — negatives shouldn't grow proportionally to size, and vars are
     handled in (1).

The "build from vanilla, transform with regex, write with a generated header"
pattern follows the sibling `multi-megastructures` mod so future patches can
be re-absorbed by re-running this script.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

MULTIPLIER = 3

SCRIPT_DIR = Path(__file__).resolve().parent
MOD_DIR = SCRIPT_DIR.parent / "mod"
DEPOSITS_OUT = MOD_DIR / "common" / "deposits"
VARIABLES_OUT = MOD_DIR / "common" / "scripted_variables"

VANILLA_ROOT = (
    Path.home()
    / "Library"
    / "Application Support"
    / "Steam"
    / "steamapps"
    / "common"
    / "Stellaris"
)
VANILLA_DEPOSITS = VANILLA_ROOT / "common" / "deposits"
VANILLA_VARIABLES = VANILLA_ROOT / "common" / "scripted_variables"

# Variables to triple. Read from vanilla so we don't hard-code values that may
# drift across patches.
SIZE_VARS = (
    "habitable_planet_max_size",
    "habitable_planet_min_size",
    "habitable_moon_max_size",
    "habitable_moon_min_size",
)
DISTRICT_VARS = (
    "DISTRICTS_FROM_SR_DEPOSITS",
    "DISTRICTS_FROM_SR_DEPOSITS_SMALL",
)

VAR_RE = re.compile(r"^@([A-Za-z_][A-Za-z_0-9]*)\s*=\s*([0-9]+)\s*$", re.MULTILINE)

# Matches `district_<thing>_max_add = N`, `district_<thing>_min_add = N`, or
# `planet_max_districts_add = N` where N is a non-negative integer (optionally
# signed +). Negative values are excluded so blocker penalties stay at vanilla
# magnitude — they're handled by the byte-for-byte negative-preservation check
# in preflight C5.
DISTRICT_NUM_RE = re.compile(
    r"(\b(?:district_[A-Za-z_]+?_(?:max|min)_add|planet_max_districts_add)"
    r"\s*=\s*)\+?([0-9]+)\b"
)

# Matches one `name = number` line inside a `produces = { ... }` block. The
# block scanner below feeds it the body only.
PRODUCES_NUM_RE = re.compile(
    r"(\b[A-Za-z_][A-Za-z_0-9]*\s*=\s*)\+?([0-9]+(?:\.[0-9]+)?)\b"
)


def discover_var_values() -> dict[str, int]:
    """Scan vanilla scripted_variables for the constants we care about, so the
    multiplied values are derived from current vanilla rather than hard-coded.
    Files are processed in sorted order so first-match-wins is deterministic
    and matches Paradox's own alphabetical load order."""
    wanted = set(SIZE_VARS) | set(DISTRICT_VARS)
    found: dict[str, int] = {}
    for path in sorted(VANILLA_VARIABLES.glob("*.txt")):
        for m in VAR_RE.finditer(path.read_text(encoding="utf-8")):
            name = m.group(1)
            if name in wanted and name not in found:
                found[name] = int(m.group(2))
    missing = wanted - set(found)
    if missing:
        raise SystemExit(f"ERROR: vanilla scripted_variables missing: {sorted(missing)}")
    return found


def write_variables_override(values: dict[str, int]) -> Path:
    VARIABLES_OUT.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by apps/mods/stellaris/3x-bigger-worlds/scripts/build.py",
        "# Source: vanilla Stellaris common/scripted_variables/*.txt",
        f"# Multiplier: x{MULTIPLIER}",
        "# Filename prefix `zz_` ensures we redefine AFTER vanilla's `100_*` files",
        "# (Paradox loads scripted_variables alphabetically; last definition wins).",
        "",
    ]
    for name in (*SIZE_VARS, *DISTRICT_VARS):
        vanilla = values[name]
        new = vanilla * MULTIPLIER
        lines.append(f"@{name} = {new}\t# vanilla {vanilla}")
    lines.append("")
    out = VARIABLES_OUT / "zz_bworlds_planet_sizes.txt"
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


def transform_districts(text: str) -> tuple[str, int]:
    def repl(m: re.Match[str]) -> str:
        return f"{m.group(1)}{int(m.group(2)) * MULTIPLIER}"

    new_text, n = DISTRICT_NUM_RE.subn(repl, text)
    return new_text, n


def transform_produces(text: str, source_name: str = "<unknown>") -> tuple[str, int]:
    """Walk top-level `produces = { ... }` blocks and triple every numeric
    `resource = N` inside. Uses a brace-depth scanner so nested braces (rare
    here, but defensive) don't break the match.

    If a `produces` block has unbalanced braces, we bail out and emit the
    remainder of the file unchanged — but we *also* warn loudly to stderr,
    because the silent fallback would leave every later `produces` block in
    that file at vanilla magnitude and the file would still preflight C1-clean
    (brace balance is computed file-wide, not block-wide). Preflight C4 would
    eventually catch it via the sequence-length mismatch, but the warning is
    the closer-to-source signal."""
    out_parts: list[str] = []
    i = 0
    total = 0
    pattern = re.compile(r"produces\s*=\s*\{")
    while True:
        m = pattern.search(text, i)
        if not m:
            out_parts.append(text[i:])
            break
        out_parts.append(text[i : m.end()])
        depth = 1
        j = m.end()
        while j < len(text) and depth:
            c = text[j]
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    break
            j += 1
        if depth != 0:
            print(
                f"WARN: {source_name} has unbalanced `produces` block at "
                f"offset {m.start()}; emitting remainder of file unchanged. "
                f"Later produces blocks in this file will NOT be tripled — "
                f"preflight C4 will fail until vanilla is fixed or build.py "
                f"is updated.",
                file=sys.stderr,
            )
            out_parts.append(text[m.end() :])
            break
        body = text[m.end() : j]

        def repl(mm: re.Match[str]) -> str:
            num = mm.group(2)
            if "." in num:
                new_val = f"{float(num) * MULTIPLIER:g}"
            else:
                new_val = str(int(num) * MULTIPLIER)
            return f"{mm.group(1)}{new_val}"

        new_body, n = PRODUCES_NUM_RE.subn(repl, body)
        total += n
        out_parts.append(new_body)
        out_parts.append(text[j])  # the closing brace
        i = j + 1
    return "".join(out_parts), total


def transform(text: str, source_name: str = "<unknown>") -> tuple[str, int, int]:
    text, n_districts = transform_districts(text)
    text, n_produces = transform_produces(text, source_name)
    return text, n_districts, n_produces


def deposit_header() -> str:
    return (
        "# Generated by apps/mods/stellaris/3x-bigger-worlds/scripts/build.py\n"
        f"# Multiplier: x{MULTIPLIER}\n"
        "# Transformations:\n"
        "#   district_*_max_add        = N  ->  N * 3   (N > 0 only)\n"
        "#   district_*_min_add        = N  ->  N * 3   (N > 0 only)\n"
        "#   planet_max_districts_add  = N  ->  N * 3   (N > 0 only)\n"
        "#   produces = { res = N }    ->  res = N * 3  (positive numeric only)\n"
        "# Untouched:\n"
        "#   Negative values (blocker penalties stay at vanilla magnitude).\n"
        "#   `@VAR` references (handled in scripted_variables/zz_bworlds_*).\n"
        "#   `upkeep = { ... }` blocks (net deposit output therefore skews\n"
        "#   3x-favorable on deposits with upkeep; see README).\n"
        "\n"
    )


def main() -> int:
    if not VANILLA_ROOT.exists():
        print(f"ERROR: Stellaris not found at {VANILLA_ROOT}", file=sys.stderr)
        return 1
    if not VANILLA_DEPOSITS.exists() or not VANILLA_VARIABLES.exists():
        print(f"ERROR: vanilla subdirs missing under {VANILLA_ROOT}", file=sys.stderr)
        return 1

    DEPOSITS_OUT.mkdir(parents=True, exist_ok=True)

    values = discover_var_values()
    var_path = write_variables_override(values)
    print(f"Wrote {var_path.relative_to(MOD_DIR)}")
    for name in (*SIZE_VARS, *DISTRICT_VARS):
        print(f"  @{name}: {values[name]} -> {values[name] * MULTIPLIER}")

    # Clear stale outputs so deleted vanilla files don't linger in the override.
    for stale in DEPOSITS_OUT.glob("*.txt"):
        stale.unlink()

    hdr = deposit_header()
    files_written = 0
    total_districts = 0
    total_produces = 0
    for src in sorted(VANILLA_DEPOSITS.glob("*.txt")):
        original = src.read_text(encoding="utf-8")
        transformed, n_d, n_p = transform(original, src.name)
        dest = DEPOSITS_OUT / src.name
        dest.write_text(hdr + transformed, encoding="utf-8")
        files_written += 1
        total_districts += n_d
        total_produces += n_p
        print(f"  {src.name}: +{n_d} district modifiers, +{n_p} produces values")

    print(
        f"\nWrote {files_written} deposit overrides "
        f"({total_districts} district mods, {total_produces} produces values multiplied) "
        f"to {DEPOSITS_OUT}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
